### ISSUE TITLE
set up user auth 

### ISSUE THREAD

**Issue by Yepez1997** [Yepez1997/lyricalgenius#3]
should set up user auth for log in and log out

**Comment by ronilbhatia** [comment]
[ ]

**Comment by Yepez1997** [comment]
user auth done with styling

**Comment by ronilbhatia** [comment]
# User Auth

## Functionality

- [ ] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [ ] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [ ] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [ ] Errors should clear when moving between `/signup` and `/login`.
- [ ] Can sign up a user
- [ ] Can sign in as a user
- [ ] Can log out a user
- [ ] Can't sign up with the same username/email
- [ ] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [ ] Should not be able to visit `/login` or `/signup`
- [ ] Should be able to refresh the page and still be logged in


## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [ ] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [ ] Remove Redux logger and all console.log()'s from production

## Seeds
- [ ] Adequate and appropriate seeds

**Comment by ronilbhatia** [comment]
You need to have checklists like the one I posted above for every issue that you submit. A lot of these checkboxes are not complete right now (like you mentioned login/signup is broken on Heroku) so you need to fix those. I've checked off the ones that I see as complete but as of right now 14/17 are not.

In terms of styling, here are my notes:

![Screen Shot 2019-05-02 at 4 17 33 PM](https://user-images.githubusercontent.com/32026924/57112851-b111d000-6cf6-11e9-861e-cce2a0c24acb.png)
![Screen Shot 2019-05-02 at 4 17 35 PM](https://user-images.githubusercontent.com/32026924/57112852-b111d000-6cf6-11e9-944f-76c9f5f8cec2.png)

Overall, styling of the Splash page is really good, but a few points:
1. When I hover over 'Login' or 'Signup' the text moves up, and the 'Lyrical Genius' logo in the middle shifts left. This is not good. All the elements should be fixed in place, and on hover the red line should go to the very bottom of the yellow bar, right now it is floating above.
2. Placeholder text in the search bar should be smaller, and black.
3. The black bar below the yellow bar is about twice as tall as the one on Genius' site.
4. I would make a logo or at least use a more interesting font for 'Lyrical Genius' - right now it is very dull.

![Screen Shot 2019-05-02 at 4 19 01 PM](https://user-images.githubusercontent.com/32026924/57112924-1f569280-6cf7-11e9-97eb-0d115a659b41.png)
![Screen Shot 2019-05-02 at 4 19 03 PM](https://user-images.githubusercontent.com/32026924/57112925-1fef2900-6cf7-11e9-93a2-fa98485e778c.png)

5. Too much padding at the top and sides of the modal.
6. Modal is way too small compared to Genius'.
7. Input boxes need to be bigger, need padding, and need to have a white background.
8. You need to add a link to signup in the login modal and vice versa. The 'Already have an account? Sign in here' part of Genius' modal.
